import { type TenantScopedDatabase } from '@odudu/db';
import { clients } from '@odudu/domain-tenant';
import { and, eq } from 'drizzle-orm';
import { clientOidcConfig } from '#/schema/client-oidc-config';
import { tokenGrants, type TokenGrantRecord } from '#/schema/token-grants';

export type { TokenGrantRecord } from '#/schema/token-grants';

// Front-Channel §3 and Back-Channel §2.3's "set of logged-in RPs" for a
// session: enough of each distinct client's logout metadata to build both
// kinds of logout request, none of the rest of its configuration. `clientId`
// is the clients table's own surrogate id — the delivery queue's foreign
// key wants exactly that — while `oauthClientId` is the client_id string a
// Logout Token's `aud` must carry (Back-Channel Logout §2.4); front-channel
// logout needs neither for anything beyond distinguishing rows.
export interface ClientLogoutTarget {
  clientId: string;
  oauthClientId: string;
  frontchannelLogoutUri: string | null;
  frontchannelLogoutSessionRequired: boolean;
  backchannelLogoutUri: string | null;
  backchannelLogoutSessionRequired: boolean;
}

function toRecord(row: typeof tokenGrants.$inferSelect): TokenGrantRecord {
  return {
    id: row.id,
    tenantId: row.tenantId,
    clientId: row.clientId,
    subjectId: row.subjectId,
    scope: row.scope,
    audience: row.audience,
    createdAt: row.createdAt,
    revokedAt: row.revokedAt,
    sessionId: row.sessionId,
    actorSubjectId: row.actorSubjectId,
    exchangedFromGrantId: row.exchangedFromGrantId,
  };
}

export interface NewTokenGrant {
  // Generated by the caller, before the access token is minted, so the
  // same id can be signed into the token's `grant_id` claim
  // (`mintAccessToken`, `token-issuance.ts`) and stored here — the only way
  // introspection or revocation can later name *this* row rather than a
  // sibling that happens to share client, subject and session.
  id: string;
  tenantId: string;
  clientId: string;
  subjectId: string;
  scope: string;
  audience: string[];
  sessionId?: string | null;
}

export function tokenGrantRepository(tx: TenantScopedDatabase) {
  return {
    async create(input: NewTokenGrant): Promise<TokenGrantRecord> {
      const rows = await tx
        .insert(tokenGrants)
        .values({
          id: input.id,
          tenantId: input.tenantId,
          clientId: input.clientId,
          subjectId: input.subjectId,
          scope: input.scope,
          audience: input.audience,
          sessionId: input.sessionId ?? null,
        })
        .returning();
      const row = rows[0];
      if (row === undefined) {
        throw new Error('insert into token_grants returned no row');
      }
      return toRecord(row);
    },

    // RFC 6749 §4.1.2: on detected authorization-code reuse, the tokens
    // issued from the first (legitimate) redemption are revoked, not just
    // the replay rejected. Idempotent — revoking an already-revoked grant
    // is a no-op, not an error.
    async revoke(id: string, revokedAt: Date): Promise<void> {
      await tx.update(tokenGrants).set({ revokedAt }).where(eq(tokenGrants.id, id));
    },

    async byId(id: string): Promise<TokenGrantRecord | null> {
      const rows = await tx.select().from(tokenGrants).where(eq(tokenGrants.id, id));
      const row = rows[0];
      return row === undefined ? null : toRecord(row);
    },

    // Logout's whole write. Returns the number revoked so a caller can tell
    // "ended a session that had grants" from "ended one that had none"
    // without a second query; an already-revoked grant is matched again and
    // simply re-stamped, which keeps this idempotent.
    async revokeForSession(sessionId: string, revokedAt: Date): Promise<number> {
      const rows = await tx
        .update(tokenGrants)
        .set({ revokedAt })
        .where(eq(tokenGrants.sessionId, sessionId))
        .returning({ id: tokenGrants.id });
      return rows.length;
    },

    async bySession(sessionId: string): Promise<TokenGrantRecord[]> {
      const rows = await tx.select().from(tokenGrants).where(eq(tokenGrants.sessionId, sessionId));
      return rows.map(toRecord);
    },

    // Front-Channel §2 and Back-Channel §2.3's "set of logged-in RPs": the
    // distinct clients that hold a grant issued under this session.
    // `token_grants.client_id` and `client_oidc_config.client_id` are both
    // the clients table's surrogate id, never the OAuth client_id string,
    // so the join needs no third table. Filtered to `enabled`, the same way
    // `webOriginsForTenant` (client-oidc-config.ts) is.
    async clientsForSession(sessionId: string): Promise<ClientLogoutTarget[]> {
      const rows = await tx
        .selectDistinct({
          clientId: clientOidcConfig.clientId,
          oauthClientId: clients.clientId,
          frontchannelLogoutUri: clientOidcConfig.frontchannelLogoutUri,
          frontchannelLogoutSessionRequired: clientOidcConfig.frontchannelLogoutSessionRequired,
          backchannelLogoutUri: clientOidcConfig.backchannelLogoutUri,
          backchannelLogoutSessionRequired: clientOidcConfig.backchannelLogoutSessionRequired,
        })
        .from(tokenGrants)
        .innerJoin(clientOidcConfig, eq(clientOidcConfig.clientId, tokenGrants.clientId))
        .innerJoin(clients, eq(clients.id, tokenGrants.clientId))
        .where(and(eq(tokenGrants.sessionId, sessionId), eq(clients.enabled, true)));
      return rows;
    },
  };
}
