import { useId, type ReactNode } from 'react';
import { Link } from 'react-aria-components';
import {
  credentialsOf,
  factorLabel,
  lockoutSummary,
  removeFactorLabel,
  REQUIRED_ACTIONS,
  type Credential,
  type Lockout,
  type Subject,
} from '#/features/subjects/service.ts';
import {
  useSubjectCredentials,
  type Asking,
  type SubjectCredentials,
} from '#/features/subjects/usecase/useSubjectCredentials.ts';
import {
  useSubjectMail,
  type MailOutcome,
  type SubjectMail,
} from '#/features/subjects/usecase/useSubjectMail.ts';
import { Button } from '#/shared/view/Button.tsx';
import { ChecklistField } from '#/shared/view/ChecklistField.tsx';
import { ConfirmDialog } from '#/shared/view/ConfirmDialog.tsx';
import { DataTable, type Column } from '#/shared/view/DataTable.tsx';
import { EmptyState } from '#/shared/view/EmptyState.tsx';
import { SecretDialog } from '#/shared/view/SecretDialog.tsx';
import { FormSkeleton } from '#/shared/view/Skeleton.tsx';
import { StatusTag } from '#/shared/view/StatusTag.tsx';
import { Timestamp } from '#/shared/view/Timestamp.tsx';
import styles from '#/features/subjects/view/Tab.module.css';

interface TabProps {
  tenant: string;
  subject: Subject;
  etag: string;
  gone: boolean;
  canManage: boolean;
  self: boolean;
}

function Panel({ title, children }: { title: string; children: ReactNode }) {
  const heading = useId();
  return (
    <section aria-labelledby={heading} className={styles.panel}>
      <h2 id={heading} className={styles.heading}>
        {title}
      </h2>
      {children}
    </section>
  );
}

function Failed({ what, retry }: { what: string; retry: () => void }) {
  return (
    <EmptyState
      variant="failed"
      title={`${what} could not be loaded`}
      action={<Button onPress={retry}>Try again</Button>}
    >
      The gateway did not answer, or answered with an error.
    </EmptyState>
  );
}

function Outcome({ outcome }: { outcome: MailOutcome | null }) {
  return (
    <p role="status" className={styles.message}>
      {outcome === null ? null : (
        <>
          {outcome.text}
          {outcome.fix === null ? null : (
            <>
              {' '}
              <Link href={outcome.fix.href}>{outcome.fix.label}</Link>
            </>
          )}
        </>
      )}
    </p>
  );
}

function Password({
  password,
  page,
  mail,
  canManage,
}: {
  password: Credential | null;
  page: SubjectCredentials;
  mail: SubjectMail;
  canManage: boolean;
}) {
  return (
    <Panel title="Password">
      <p className={styles.text}>
        {password === null ? (
          `${page.name} has no password yet.`
        ) : (
          <>
            {`Set `}
            <Timestamp value={password.created_at} />
            {password.expired === true ? (
              <>
                {' '}
                <StatusTag tone="warning">expired</StatusTag> It must be changed at the next
                sign-in.
              </>
            ) : null}
          </>
        )}
      </p>
      <p className={styles.rule}>
        Nobody chooses a password here. A reset email lets the subject choose one from their own
        mailbox; a one-time password is generated by the server, shown to you once, and must be
        changed at the next sign-in.
      </p>
      {canManage && mail.email === null ? (
        <p className={styles.rule}>
          {`${page.name} has no email address, so no reset link can be sent: a one-time password is the way.`}
        </p>
      ) : null}
      {canManage ? (
        <div className={styles.actions}>
          {mail.email === null ? null : (
            <Button variant="primary" isDisabled={mail.reset.busy} onPress={mail.reset.send}>
              Send a password reset email
            </Button>
          )}
          <Button
            onPress={() => {
              page.ask({ kind: 'password' });
            }}
          >
            Issue a one-time password
          </Button>
        </div>
      ) : null}
      <Outcome outcome={mail.reset.outcome} />
    </Panel>
  );
}

function Factors({
  factors,
  page,
  canManage,
}: {
  factors: readonly Credential[];
  page: SubjectCredentials;
  canManage: boolean;
}) {
  const columns: Column<Credential>[] = [
    {
      id: 'type',
      header: 'Factor',
      isRowHeader: true,
      cell: (credential) => factorLabel(credential.type),
    },
    {
      id: 'created_at',
      header: 'Enrolled',
      cell: (credential) => <Timestamp value={credential.created_at} />,
    },
  ];
  if (canManage) {
    columns.push({
      id: 'remove',
      header: 'Action',
      cell: (credential) => (
        <Button
          size="small"
          variant="quiet"
          aria-label={removeFactorLabel(credential)}
          onPress={() => {
            page.ask({ kind: 'factor', credential });
          }}
        >
          Remove
        </Button>
      ),
    });
  }
  return (
    <Panel title="Second factors">
      <DataTable
        label={`Second factors of ${page.name}`}
        columns={columns}
        rows={factors}
        rowKey={(credential) => credential.id ?? credential.type}
        empty={`${page.name} has no authenticator app or passkey enrolled.`}
      />
      <p className={styles.rule}>
        Removing a factor means the next sign-in no longer offers or asks for it. To have one
        enrolled again, require it among the subject&apos;s required actions.
      </p>
    </Panel>
  );
}

function RecoveryCodes({
  count,
  page,
  canManage,
}: {
  count: number | null;
  page: SubjectCredentials;
  canManage: boolean;
}) {
  return (
    <Panel title="Recovery codes">
      <p className={styles.text}>
        {count === null || count === 0
          ? `No recovery codes: ${page.name} holds no unspent one.`
          : count === 1
            ? '1 unspent recovery code'
            : `${String(count)} unspent recovery codes`}
      </p>
      <p className={styles.rule}>
        Codes are shown only to the subject, once, and carry no id of their own, so the set is
        revoked whole or not at all.
      </p>
      {canManage && count !== null && count > 0 ? (
        <div className={styles.actions}>
          <Button
            variant="danger"
            onPress={() => {
              page.ask({ kind: 'recovery-codes' });
            }}
          >
            Revoke every recovery code
          </Button>
        </div>
      ) : null}
    </Panel>
  );
}

function LockoutPanel({
  lockout,
  page,
  canManage,
}: {
  lockout: Lockout;
  page: SubjectCredentials;
  canManage: boolean;
}) {
  const summary = lockoutSummary(lockout);
  return (
    <Panel title="Lockout">
      <p className={styles.text}>
        <StatusTag tone={summary.tone}>{summary.state}</StatusTag> {summary.text}
      </p>
      {lockout.locked_until === null && lockout.last_failure_at === null ? null : (
        <dl className={styles.fixed}>
          {lockout.locked_until === null ? null : (
            <>
              <dt>{lockout.locked ? 'Locked until' : 'Last lock ended'}</dt>
              <dd>
                <Timestamp value={lockout.locked_until} />
              </dd>
            </>
          )}
          {lockout.last_failure_at === null ? null : (
            <>
              <dt>Last failed sign-in</dt>
              <dd>
                <Timestamp value={lockout.last_failure_at} />
              </dd>
            </>
          )}
        </dl>
      )}
      {canManage && lockout.failure_count > 0 ? (
        <div className={styles.actions}>
          <Button
            onPress={() => {
              page.ask({ kind: 'lockout' });
            }}
          >
            Clear the lockout
          </Button>
        </div>
      ) : null}
    </Panel>
  );
}

const ACTION_OPTIONS = REQUIRED_ACTIONS.map(({ action, label, description }) => ({
  id: action,
  label,
  description,
}));

function Email({ name, mail }: { name: string; mail: SubjectMail }) {
  const { actions } = mail;
  if (mail.email === null) {
    return (
      <Panel title="Email">
        <p className={styles.rule}>
          {`${name} has no email address, so nothing can be mailed. Add one under Profile.`}
        </p>
      </Panel>
    );
  }
  return (
    <Panel title="Email">
      <p className={styles.rule}>
        {`Each link goes to ${mail.email}, and is never shown here. Nothing is sent until the tenant can send mail.`}
      </p>
      <div className={styles.actions}>
        <Button isDisabled={mail.verification.busy} onPress={mail.verification.send}>
          Send a verification email
        </Button>
      </div>
      <Outcome outcome={mail.verification.outcome} />
      <form
        noValidate
        className={styles.form}
        onSubmit={(event) => {
          event.preventDefault();
          actions.send();
        }}
      >
        <ChecklistField
          label="Required actions to email"
          description="The link takes the subject through these in order. A password is set from the link itself; a factor is enrolled only after signing in."
          options={ACTION_OPTIONS}
          value={actions.actions}
          error={actions.errors.actions}
          onChange={actions.choose}
        />
        <div className={styles.actions}>
          <Button type="submit" isDisabled={actions.busy}>
            Email required actions
          </Button>
        </div>
      </form>
      <Outcome outcome={actions.outcome} />
    </Panel>
  );
}

interface Dialog {
  title: string;
  consequence: string;
  confirmLabel: string;
  tone: 'primary' | 'danger';
}

function dialogOf(asking: Asking, name: string, self: boolean): Dialog {
  switch (asking.kind) {
    case 'password':
      return {
        title: `Issue ${name} a one-time password?`,
        consequence: self
          ? 'This replaces your own password, and you must change it at your next sign-in. Any lockout is cleared. No session ends, this one included.'
          : `This replaces the password ${name} has, and they must change it at their next sign-in. Any lockout is cleared. No session ends and no grant is revoked.`,
        confirmLabel: 'Issue password',
        tone: 'primary',
      };
    case 'factor': {
      const label = factorLabel(asking.credential.type);
      const lowered = `${label.charAt(0).toLowerCase()}${label.slice(1)}`;
      return {
        title: `Remove ${name}’s ${lowered}?`,
        consequence: `${name}'s next sign-in no longer offers or asks for this ${lowered}. Signing in with it again needs a new enrolment.`,
        confirmLabel: 'Remove',
        tone: 'danger',
      };
    }
    case 'recovery-codes':
      return {
        title: `Revoke ${name}’s recovery codes?`,
        consequence: `Every recovery code ${name} holds stops working, unspent ones too. They get a fresh set only when one is asked of them, as the generate-recovery-codes required action.`,
        confirmLabel: 'Revoke recovery codes',
        tone: 'danger',
      };
    case 'lockout':
      return {
        title: `Clear ${name}’s lockout?`,
        consequence: `The run of failed sign-ins is forgotten, so ${name}'s next right password signs in at once, and the next wrong one counts from one.`,
        confirmLabel: 'Clear lockout',
        tone: 'primary',
      };
  }
}

function Held({
  page,
  mail,
  canManage,
}: {
  page: SubjectCredentials;
  mail: SubjectMail;
  canManage: boolean;
}) {
  const { credentials, lockout } = page;
  return (
    <>
      {credentials.status === 'loading' ? (
        <FormSkeleton label="Loading credentials" />
      ) : credentials.status === 'failed' ? (
        <Failed what="The credentials" retry={credentials.retry} />
      ) : (
        (() => {
          const held = credentialsOf(credentials.data.items);
          return (
            <>
              <Password password={held.password} page={page} mail={mail} canManage={canManage} />
              <Factors factors={held.factors} page={page} canManage={canManage} />
              <RecoveryCodes count={held.recoveryCodes} page={page} canManage={canManage} />
            </>
          );
        })()
      )}
      {lockout.status === 'loading' ? (
        <FormSkeleton label="Loading the lockout" fields={2} />
      ) : lockout.status === 'failed' ? (
        <Failed what="The lockout" retry={lockout.retry} />
      ) : (
        <LockoutPanel lockout={lockout.data} page={page} canManage={canManage} />
      )}
      {canManage ? <Email name={page.name} mail={mail} /> : null}
    </>
  );
}

export function CredentialsTab({ tenant, subject, canManage, self }: TabProps) {
  const page = useSubjectCredentials(tenant, subject);
  const mail = useSubjectMail(tenant, subject);
  const dialog = page.asking === null ? null : dialogOf(page.asking, page.name, self);
  return (
    <div className={styles.tab}>
      {page.itself ? (
        <p className={styles.text}>
          {`A ${subject.type} subject signs in as itself, with its client's credentials: it has no password, second factor, recovery code or lockout.`}
        </p>
      ) : (
        <Held page={page} mail={mail} canManage={canManage} />
      )}
      <ConfirmDialog
        isOpen={dialog !== null}
        title={dialog?.title ?? ''}
        consequence={dialog?.consequence ?? ''}
        confirmLabel={dialog?.confirmLabel ?? ''}
        tone={dialog?.tone ?? 'primary'}
        busy={page.busy}
        problem={page.problem}
        onConfirm={page.confirm}
        onCancel={page.cancel}
      />
      <SecretDialog
        secret={page.secret}
        title={`${page.name}'s one-time password`}
        label="one-time password"
        onClose={page.closeSecret}
      >
        {`Give it to ${page.name} by a channel you trust. They must change it at their next sign-in.`}
      </SecretDialog>
    </div>
  );
}
