import { describe, expect, it, vi } from 'vitest';
import type * as NodeCrypto from 'node:crypto';

// A mock whose default implementation is the real randomBytes, so every
// test but the one below still gets real IVs; that one test overrides it
// for exactly two calls to make "byte for byte" a real comparison — AES-GCM's
// own randomness would otherwise make wrapPrivateJwk and wrapSecret's output
// differ regardless of whether they share an implementation.
const { randomBytesMock } = vi.hoisted(() => ({ randomBytesMock: vi.fn() }));
vi.mock('node:crypto', async (importOriginal) => {
  const actual = await importOriginal<typeof NodeCrypto>();
  randomBytesMock.mockImplementation(actual.randomBytes);
  return { ...actual, randomBytes: randomBytesMock };
});

import { unwrapPrivateJwk, unwrapSecret, wrapPrivateJwk, wrapSecret } from '#/service/kek';

const KEK = new Uint8Array(32).fill(7);
const JWK = { kty: 'RSA', n: 'abc', e: 'AQAB', d: 'secret-private-exponent' };

// Produced by wrapPrivateJwk(JWK, KEK) at commit b89eeb0, the last commit
// before this envelope was generalised — a real historical artefact, not
// one generated by the code under test, so it actually exercises "does an
// already-stored key still unwrap" rather than assuming the answer.
const STORED_AT_B89EEB0 =
  '6YHmNQNT1frbzjjyXmIhc6fWAyqjfkaA7L4xe6d0UX2DNPlcNJmlLcCK957QXLBFnc5vhOacjjoY9tXyHGAQLlnBYBaqpq0f0pk1phf2SjKLxX94dY60CXP+JNM=';

describe('KEK wrapping', () => {
  it('round-trips a private JWK', () => {
    expect(unwrapPrivateJwk(wrapPrivateJwk(JWK, KEK), KEK)).toEqual(JWK);
  });

  it('produces different ciphertext each time for the same input', () => {
    expect(wrapPrivateJwk(JWK, KEK)).not.toEqual(wrapPrivateJwk(JWK, KEK));
  });

  it('never leaves the private exponent readable in the wrapped form', () => {
    expect(wrapPrivateJwk(JWK, KEK)).not.toContain('secret-private-exponent');
  });

  it('refuses to unwrap with the wrong key rather than returning garbage', () => {
    const wrong = new Uint8Array(32).fill(8);
    expect(() => unwrapPrivateJwk(wrapPrivateJwk(JWK, KEK), wrong)).toThrow();
  });

  it('refuses to unwrap tampered ciphertext', () => {
    const wrapped = wrapPrivateJwk(JWK, KEK);
    expect(() => unwrapPrivateJwk(wrapped.slice(0, -4) + 'AAAA', KEK)).toThrow();
  });

  it('rejects a key that is not 32 bytes', () => {
    expect(() => wrapPrivateJwk(JWK, new Uint8Array(16))).toThrow(/32 bytes/);
  });

  it('still unwraps a JWK stored before this envelope was generalised', () => {
    expect(unwrapPrivateJwk(STORED_AT_B89EEB0, KEK)).toEqual(JWK);
  });
});

describe('wrapSecret', () => {
  it('round-trips an arbitrary string', () => {
    expect(unwrapSecret(wrapSecret('hunter2', KEK), KEK)).toBe('hunter2');
  });

  it('refuses a wrong key rather than returning rubbish', () => {
    const wrapped = wrapSecret('hunter2', KEK);
    const wrong = new Uint8Array(32).fill(8);
    expect(() => unwrapSecret(wrapped, wrong)).toThrow();
  });

  it('unwraps a JWK stored before this envelope was generalised', () => {
    expect(JSON.parse(unwrapSecret(STORED_AT_B89EEB0, KEK))).toEqual(JWK);
  });

  // "The same key-encryption interface as a signing key" has to mean one
  // implementation, or it is two implementations that merely agree today.
  // With the IV fixed to the same value for both calls, byte-identical
  // output is only possible if wrapPrivateJwk is wrapSecret underneath —
  // any second implementation, however faithful, would need its own IV
  // draw and could not land on the same bytes by coincidence.
  it('is the same envelope wrapPrivateJwk produces, byte for byte', () => {
    const fixedIv = Buffer.alloc(12, 3);
    randomBytesMock.mockReturnValueOnce(fixedIv).mockReturnValueOnce(fixedIv);

    const viaWrapSecret = wrapSecret(JSON.stringify(JWK), KEK);
    const viaWrapPrivateJwk = wrapPrivateJwk(JWK, KEK);

    expect(viaWrapPrivateJwk).toBe(viaWrapSecret);
  });
});
