export {
  clientsHref,
  newClientHref,
  clientHref,
  clientsTrail,
} from '#/features/clients/service/address.ts';
export {
  CLIENT_TABS,
  type ClientTab,
  CLIENT_TAB_LABELS,
  clientTabHref,
  chosenTab,
  clientRecord,
  tabsWithEdits,
} from '#/features/clients/service/tabs.ts';
export {
  DESCRIPTION_MAX,
  DESCRIPTION_RULE,
  CLIENT_ID_FIXED,
  TYPE_FIXED,
  CLIENT_ID_TAKEN,
  REDIRECTS_RULE,
  ORIGINS_RULE,
  PAGES_RULE,
  POST_LOGOUT_NOTE,
  registeredText,
  TYPE_TEXT,
  SECTION,
  FIELD,
  ACTIVITY_NOTE,
} from '#/features/clients/service/labels.ts';
export {
  type Reach,
  clientReach,
  canChange,
  reachLine,
} from '#/features/clients/service/ceiling.ts';
export {
  type Fixable,
  enabledFixed,
  redirectsFixed,
  listsReadOnly,
  deleteFixed,
  scopesFixed,
} from '#/features/clients/service/blocks.ts';
export { deleteConsequence, deletedText } from '#/features/clients/service/confirm.ts';
export {
  type NewClientKind,
  type NewClientField,
  type KindChoice,
  KIND_CHOICES,
  NEW_CLIENT_FIELDS,
  newClientKind,
  asksRedirects,
  splitSecret,
  afterCreation,
  clientIdProblem,
  SECRET_LABEL,
  secretTitle,
  secretNote,
} from '#/features/clients/service/create.ts';
export {
  CLIENT_LIST_LIMIT,
  entriesOf,
  listCount,
  namesText,
} from '#/features/clients/service/lists.ts';
export {
  CLIENT_CAPABILITY,
  ceilingRefused,
  clientRefusal,
} from '#/features/clients/service/refusal.ts';
export {
  AUTH_TIME_LABEL,
  AUTH_TIME_RULE,
  CREDENTIALS_NOUN,
  CREDENTIALS_RULE,
  FULL_SCOPE_RULE,
  GRANT_LABELS,
  GRANTS_RULE,
  grantOptions,
  grantsBlock,
  ID_TOKEN_ALG_RULE,
  idTokenAlgOptions,
  ID_TOKEN_ALG_LABEL,
  LIFETIME_LABELS,
  LIFETIMES,
  lifetimeBounds,
  lifetimeText,
  maxAgeText,
  numberKept,
  REQUIRE_AUTH_TIME_NOTE,
  lifetimeRule,
  MAX_AGE_LABEL,
  MAX_AGE_MAX,
  MAX_AGE_OFF,
  MAX_AGE_RULE,
  MAX_AGE_START,
  SECTIONS_TOKENS,
  TOKEN_FIELD,
  tenantLifetimeLabel,
  type Lifetime,
} from '#/features/clients/service/tokens.ts';
export { AUTO, choiceOf, sentOf } from '#/features/clients/service/choices.ts';
export {
  authNote,
  authOptions,
  authPayload,
  encryptsUserinfo,
  AUDIENCES_RULE,
  EXCHANGE_LABEL,
  EXCHANGE_RULE,
  FIXED_BY_DESIGN,
  keysProblem,
  KEYS_BLOCKED,
  type KeysProblem,
  jwksText,
  JWKS_URI_RULE,
  KEY_SOURCES,
  KEYS_RULE,
  keysPayload,
  keySourceOf,
  needsSubjectDn,
  parseJwks,
  PUBLIC_AUTH_FIXED,
  PUBLIC_SECRET_FIXED,
  SECRET_RULE,
  SECTIONS_ADVANCED,
  SUBJECT_DN_RULE,
  userinfoContentOptions,
  userinfoEncryptionOptions,
  userinfoPayload,
  userinfoSigningOptions,
  USERINFO_RULE,
  type KeySource,
} from '#/features/clients/service/advanced.ts';
export {
  BACKCHANNEL_RULE,
  BACKCHANNEL_SESSION_LABEL,
  BACKCHANNEL_SESSION_RULE,
  FRONTCHANNEL_RULE,
  FRONTCHANNEL_SESSION_LABEL,
  FRONTCHANNEL_SESSION_RULE,
  POST_LOGOUT_RULE,
  LOGOUT_FIELD,
  POST_LOGOUT_NOUN,
  SECTIONS_LOGOUT,
} from '#/features/clients/service/logout.ts';
export {
  GRACE_LABEL,
  GRACE_MAX,
  GRACE_RULE,
  rotationFailureText,
  rotatedNote,
  rotatedTitle,
  rotateConsequence,
} from '#/features/clients/service/secret.ts';
export {
  alreadyAssigned,
  ASSIGN_HEADING,
  ASSIGN_LABEL,
  ASSIGNED_HEADING,
  ASSIGNMENT_RULE,
  ASSIGNMENTS,
  assignedText,
  assignmentOf,
  moreScopes,
  NO_SCOPES,
  PICKER_LABEL,
  scopeCount,
  scopeFailureText,
  scopeRefusal,
  SCOPES_CAPABILITY,
  SCOPES_PAGE,
  shownScopes,
  unassignedText,
} from '#/features/clients/service/scopes.ts';
export {
  assignedCount,
  assignedRoles,
  nameIndex,
  roleNameOf,
  type AssignedRole,
  heldCapabilitiesText,
  NO_ACCOUNT,
  NO_ROLES,
  roleUnavailable,
  ROLES_LABEL,
  serviceRolesRecord,
  SERVICE_CAPABILITY,
  SERVICE_RULE,
  splitAssigned,
} from '#/features/clients/service/account.ts';
export {
  CLIENT_ROLES_RULE,
  clientRolesListHref,
  NEW_ROLE_NAME_LABEL,
  ROLES_OPEN_LABEL,
  rolesReadable,
  NAME_REQUIRED,
  NEW_ROLE_HEADING,
  NEW_ROLE_RULE,
  NO_CLIENT_ROLES,
  ROLE_NAME_TAKEN,
  ROLES_CAPABILITY,
  roleOwnerLine,
} from '#/features/clients/service/roles.ts';
export {
  NO_SESSIONS,
  REVOKE_HEADING,
  REVOKE_RULE,
  revokedText,
  revokeConsequence,
  revokeFailureText,
  SESSIONS_CAPABILITY,
  SESSIONS_NOUN,
  SESSIONS_RULE,
} from '#/features/clients/service/sessions.ts';
export {
  ANY_STATUS,
  attemptsText,
  DELIVERIES_HEADING,
  DELIVERIES_RULE,
  deliveryTone,
  NO_DELIVERIES,
  STATUS_OPTIONS,
  statusFilter,
} from '#/features/clients/service/deliveries.ts';
export {
  INSTALLATION_HEADING,
  INSTALLATION_RULE,
  installationRows,
  NONE,
  type InstallationRow,
} from '#/features/clients/service/installation.ts';
export {
  artefactsOf,
  evaluatedScope,
  EVALUATE_CAPABILITY,
  EVALUATE_HEADING,
  EVALUATE_LABEL,
  EVALUATE_RULE,
  evaluateFailureText,
  NO_ID_TOKEN,
  SCOPE_LABEL,
  SCOPE_RULE,
  SUBJECT_PICKER_LABEL,
  type Artefact,
} from '#/features/clients/service/evaluate.ts';
